[[bots]]
cookie = "client_session=xxxxxx"
room = "Test"                    # the first bot in `Test`
auto_ready = true                # always ready
# the bot is in Team `0` by default

[[bots]]
cookie = "client_session=xxxxxx"
room = "Test"                    # the second bot in `Test`
auto_ready = { more_than = 3 }   # ready only when there are more than 3 players
# in Team `0` as well

[[bots]]
cookie = "client_session=xxxxxx"
room = "Test"                    # another bot in `Test`
auto_ready = { more_than = 5 }
team = 1                         # but in a different (explicitly given) team, plays against the other two bots
expand_rate = 80                 # custom expand rate

[[bots]]
cookie = "client_session=xxxxxx"
room = "随机房"                     # join a different room
auto_ready = false               # never ready

[rooms]
Test = { map = 2, speed = 4, private = true }
"随机房" = { private = false }                   # room settings are optional
